version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: oders_management
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-orders
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"